# Generated by Django 3.0.1 on 2019-12-28 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Manufactures',
            new_name='Manufacturers',
        ),
    ]
